# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DATABASE_URL=mysql://root:@127.0.0.1/guia_test

# Update composer
before-install:
  - mysql -e 'CREATE DATABASE guia_test;'
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
#  - phpunit

# After a build, send email notification with the build results
notifications:
email: loganguns@gmail.com